services:
  postgres:
    image: postgres:16
    container_name: distributed-job-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distributed_jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build: ./backend
    container_name: distributed-api
    env_file:
      - .env
    ports:
      - "5000:5000"
    command:
      - node
      - server.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  worker-1:
    build: ./backend
    container_name: distributed-worker-1
    env_file:
      - .env
    environment:
      WORKER_ID: worker-1
    command:
      - node
      - src/workers/job.worker.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  worker-2:
    build: ./backend
    container_name: distributed-worker-2
    env_file:
      - .env
    environment:
      WORKER_ID: worker-2
    command:
      - node
      - src/workers/job.worker.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  outbox:
    build: ./backend
    container_name: distributed-outbox
    env_file:
      - .env
    command:
      - node
      - src/queue/outbox.worker.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  retry-scheduler:
    build: ./backend
    container_name: distributed-retry-scheduler
    env_file:
      - .env
    command:
      - node
      - src/queue/retry.scheduler.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  reconciliation:
    build: ./backend
    container_name: distributed-reconciliation
    env_file:
      - .env
    command:
      - node
      - src/workers/reconciliation.worker.js
    restart:
      unless-stopped
    depends_on:
      - postgres

  pending-cleanup:
    build: ./backend
    container_name: distributed-pending-cleanup
    env_file:
      - .env
    command:
      - node
      - src/workers/redis.pending-cleanup.worker.js
    restart:
      unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
